/* WEATHER */

export const START_FETCHING_DAILY_WEATHER = 'START_FETCHING_DAILY_WEATHER';
export const FETCH_DAILY_WEATHER_SUCCEEDED = 'FETCH_DAILY_WEATHER_SUCCEEDED';
export const FETCH_DAILY_WEATHER_FAILED = 'FETCH_DAILY_WEATHER_FAILED';

export const START_FETCHING_CURRENT_WEATHER = 'START_FETCHING_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCEEDED = 'FETCH_CURRENT_WEATHER_SUCCEEDED';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';

export const START_FETCHING_HOURLY_WEATHER = 'START_FETCHING_HOURLY_WEATHER';
export const FETCH_HOURLY_WEATHER_SUCCEEDED = 'FETCH_HOURLY_WEATHER_SUCCEEDED';
export const FETCH_HOURLY_WEATHER_FAILED = 'FETCH_HOURLY_WEATHER_FAILED';

export const CHANGE_UNIT = 'CHANGE_UNIT';

/* NEWs */

export const START_FETCHING_NEWS = 'START_FETCHING_NEWS';
export const FETCH_NEWS_SUCCEEDED = 'FETCH_NEWS_SUCCEEDED';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

/* PLACES */

export const START_GETTING_CURRENT_CITY  = 'START_GETTING_CURRENT_CITY'
export const GET_CURRENT_CITY_SUCCEEDED = 'GET_CURRENT_CITY_SUCCEEDED';
export const GET_CURRENT_CITY_FAILED = 'GET_CURRENT_CITY_FAILED'